mqtt:
  host: 10.0.0.5
  port: 1883
  client-id: mqtt-kube
  topic-prefix: dev/mqtt-kube

http:
  host: 0.0.0.0
  port: 8080
  max-connections: 10

bindings:
  - namespace: media
    resource: Deployment
    name: jellyfin
    patch:
      topic: jellyfin/power/set
      values:
        ON: 1
        OFF: 0
      jsonpath: "spec.replicas"
    watch:
      jsonpath: "status.availableReplicas"
      values:
        1: ON
        ~: OFF
      topic: jellyfin/power/state
      retain: true
      qos: 1

  - namespace: iot
    resource: DaemonSet
    name: mqtt-ids
    patch:
      topic: mqtt-ids/power/set
      values:
        ON: rpi1
        OFF: no-node
      jsonpath: "spec.template.spec.nodeName"
    watch:
      jsonpath: "status.numberAvailable"
      values:
        1: ON
        ~: OFF
      topic: mqtt-ids/power/state
      retain: true
      qos: 1

  - namespace: dev
    job:
      spec:
        template:
          spec:
            containers:
              image: alpine
              command:
              - wget
              - http://10.0.0.5/foo
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "10m"
                limits:
                  memory: "32Mi"
                  cpu: "10m"
    trigger:
      topic: webhook/cmd
      values:
        ON: on
        OFF: off
